lang: ja-JP
permalink: /blog/:year-:month/:title
timezone: Asia/Tokyo
encoding: utf-8

theme: jekyll-theme-cayman
title: hyiromori's portfolio
description: フルスタックエンジニア hyiromori のポートフォリオサイトです。
show_downloads: false
github:
  is_project_page: false
google_analytics: UA-124358962-1

#sass:
#  style: compressed
exclude:
- .gitignore
- .ruby-version
- Gemfile
- Gemfile.lock
- README.md
- app
