lang: ja-JP
permalink: /article/:year-:month/:title
timezone: Asia/Tokyo
encoding: utf-8
sass:
  style: compressed

theme: jekyll-theme-cayman
title: hyiromori's portfolio
description: Web系フルスタックエンジニア hyiromori のポートフォリオサイトです。
show_downloads: false
github:
  is_project_page: false
google_analytics: UA-124358962-1

exclude:
- .gitignore
- .ruby-version
- Gemfile
- Gemfile.lock
- README.md
- app
