lang: ja-JP
title: Portfolio by hyiromori
description: Web系フルスタックエンジニア hyiromori のポートフォリオサイトです。
timezone: Asia/Tokyo
encoding: utf-8

permalink: /article/:year-:month/:title
sass:
  style: compressed
exclude:
- .gitignore
- .ruby-version
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- app
