#title: "hyiromori"
#description: >-
#  Portfolio
#email: "hyiromori@gmail.com"
#lang: ja-JP
#markdown: kramdown
#theme: jekyll-theme-cayman
#timezone: Asia/Tokyo
#envoding: utf-8
exclude:
- src
- .gitignore
- .tool-versions
- Gemfile
- Gemfile.log
- README.md
